### ISSUE TITLE
SQLDB is missing

### ISSUE THREAD

**Issue by Liixee** [andreklug/docspell-debian#2]
Hello,

first of all, thank you for your great instructions.

I have a suggestion for improvement: In your instructions the integration of PostgreSQL is missing in the config.

jdbc {
  url = "jdbc:postgresql://localhost:5432/docspelldb"
  user = "docspell"
  password = "xxxx!"
 }

Otherwise the database under /tmp will be deleted with every restart.

Thanks and nice greetz

**Comment by andreklug** [comment]
Hi @Liixee 

thanks a lot, I have updated the instructions.

cheers
André
