### ISSUE TITLE
Recreate fulltext index

### ISSUE THREAD

**Issue by roland6b** [andreklug/docspell-debian#3]
Hallo,
vielen Dank für die Anleitung. Ich habe die Installation nach deiner Anleitung durchgeführt und einen Verbesserungsvorschlag.
Die folgende Anweisung (mit dem passenden admin secret) erzeugt eine Fehlermeldung: "Secret invalid":
dsc -d http://localhost:7880 admin -a 'my admin secret' recreate-index

Die Hochkommas sollten wie folgt durch Anführungszeichen ersetzt werden, dann funktioniert es:

dsc -d http://localhost:7880 admin -a "my admin secret" recreate-index

Viele Grüße
Roland

**Comment by andreklug** [comment]
Danke für den Hinweis Roland, habe es aktualisiert.
